### PR TITLE
Struct functions#28

### PR DESCRIPTION
**Pull request by rafal-pracht**
Fix [28](https://github.com/Adgnitio/QuantumCircuits.jl/issues/28)

### CODE REVIEW

**Comment by rafal-pracht** [comment]
@jlapeyre could you look?

BTW, the pipeline fails because the CBOO is not Julia's package, we should add it to the repository.

**Comment by rafal-pracht** [comment]
@jlapeyre The only change in the library was the name? When I used the old one, tests locally have worked ok. 

But when I change to use the new one, there is a storage bus runtime error (exactly the same as in this PR tests).

**Comment by jlapeyre** [comment]
> But when I change to use the new one, there is a strange bus runtime error
I don't recall when I changed things. I'll look into it.

**Comment by jlapeyre** [comment]
This is really strange. I can't see any relation to CBOOCall.jl. But, there may be still. And, you did not change anything in this PR branch either ?

**Comment by jlapeyre** [comment]
I tried using an older commit of CBOO. Any indeed, the tests are passing. I need to bisect somehow to find the problem.

**Comment by jlapeyre** [comment]
CBOOCall.jl v 0.1.1 should fix this. I will be registered soon.

**Comment by rafal-pracht** [comment]
@jlapeyre Thank you, now it looks OK.

**Pull request merged**
